// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIS_DIAF.Models;

#nullable disable

namespace SIS_DIAF.Migrations
{
    [DbContext(typeof(SistemaDiafContext))]
    partial class SistemaDiafContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Archivo", b =>
                {
                    b.Property<long>("archivo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("archivo_id"));

                    b.Property<long>("RegimenId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoArchivoId")
                        .HasColumnType("bigint");

                    b.Property<string>("archivo_estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("archivo_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("archivo_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("archivo_ruta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fecha_subida")
                        .HasColumnType("datetime2");

                    b.HasKey("archivo_id");

                    b.HasIndex("RegimenId");

                    b.HasIndex("TipoArchivoId");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Historico", b =>
                {
                    b.Property<long>("historico_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("historico_id"));

                    b.Property<string>("historico_archivoRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("historico_fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("historico_guidArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("historico_guidRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("historico_tipoArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("historico_id");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Regimen", b =>
                {
                    b.Property<long>("regimen_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("regimen_id"));

                    b.Property<string>("regimen_cod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regimen_fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("regimen_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regimen_objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("regimen_presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("regimen_id");

                    b.ToTable("Regimens");
                });

            modelBuilder.Entity("SIS_DIAF.Models.ResponsableRegimen", b =>
                {
                    b.Property<int>("responsableReg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("responsableReg_id"));

                    b.Property<long?>("Regimenregimen_id")
                        .HasColumnType("bigint")
                        .HasColumnName("responsableReg_regimenId");

                    b.Property<long>("Usuariousuario_id")
                        .HasColumnType("bigint")
                        .HasColumnName("responsableReg_usuarioId");

                    b.Property<string>("responsableReg_codigoRegimen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsableReg_estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("responsableReg_id");

                    b.HasIndex("Regimenregimen_id");

                    b.HasIndex("Usuariousuario_id");

                    b.ToTable("ResponsableRegimens");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Rol", b =>
                {
                    b.Property<long>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("rol_id"));

                    b.Property<string>("rol_descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rol_estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rol_fecha_creacion")
                        .HasColumnType("datetime2");

                    b.HasKey("rol_id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("SIS_DIAF.Models.ServicioCorreo", b =>
                {
                    b.Property<string>("srVCorreo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("srvCorreo_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("srvCorreo_host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("srvCorreo_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("srvCorreo_port")
                        .HasColumnType("int");

                    b.HasKey("srVCorreo_id");

                    b.ToTable("ServicioCorreo");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Sucursal", b =>
                {
                    b.Property<long>("sucursal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("sucursal_id"));

                    b.Property<string>("sucursal_estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sucursal_fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("sucursal_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sucursal_id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("SIS_DIAF.Models.TipoArchivo", b =>
                {
                    b.Property<long>("tipoarchivo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tipoarchivo_id"));

                    b.Property<long>("TipoRegId")
                        .HasColumnType("bigint");

                    b.Property<string>("tip_descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tip_fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("tip_prioridad")
                        .HasColumnType("int");

                    b.Property<string>("tipo_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tipoarchivo_id");

                    b.HasIndex("TipoRegId");

                    b.ToTable("TipoArchivos");
                });

            modelBuilder.Entity("SIS_DIAF.Models.TipoReg", b =>
                {
                    b.Property<long>("tiporeg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tiporeg_id"));

                    b.Property<string>("nombre_tipo_reg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tipo_fecha_creacion")
                        .HasColumnType("datetime2");

                    b.HasKey("tiporeg_id");

                    b.ToTable("TipoRegs");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Usuario", b =>
                {
                    b.Property<long>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("usuario_id"));

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long>("SucursalId")
                        .HasColumnType("bigint");

                    b.Property<string>("usuario_cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("usuario_celular")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("usuario_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario_estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("usuario_guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("usuario_nIntentos")
                        .HasColumnType("int");

                    b.Property<string>("usuario_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario_passwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuario_id");

                    b.HasIndex("RolId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Archivo", b =>
                {
                    b.HasOne("SIS_DIAF.Models.Regimen", "Regimen")
                        .WithMany("Archivos")
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIS_DIAF.Models.TipoArchivo", "TipoArchivo")
                        .WithMany("Archivos")
                        .HasForeignKey("TipoArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regimen");

                    b.Navigation("TipoArchivo");
                });

            modelBuilder.Entity("SIS_DIAF.Models.ResponsableRegimen", b =>
                {
                    b.HasOne("SIS_DIAF.Models.Regimen", "regimen")
                        .WithMany("responsableRegimen")
                        .HasForeignKey("Regimenregimen_id");

                    b.HasOne("SIS_DIAF.Models.Usuario", "usuario")
                        .WithMany("responsableRegimen")
                        .HasForeignKey("Usuariousuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("regimen");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("SIS_DIAF.Models.TipoArchivo", b =>
                {
                    b.HasOne("SIS_DIAF.Models.TipoReg", "TipoReg")
                        .WithMany("TipoArchivos")
                        .HasForeignKey("TipoRegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoReg");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Usuario", b =>
                {
                    b.HasOne("SIS_DIAF.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIS_DIAF.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Regimen", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("responsableRegimen");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Sucursal", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SIS_DIAF.Models.TipoArchivo", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("SIS_DIAF.Models.TipoReg", b =>
                {
                    b.Navigation("TipoArchivos");
                });

            modelBuilder.Entity("SIS_DIAF.Models.Usuario", b =>
                {
                    b.Navigation("responsableRegimen");
                });
#pragma warning restore 612, 618
        }
    }
}
